trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'arundevc/pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build and Push an image
  inputs:
    containerRegistry: arundevc_docker_connection
    repository: $(imageName)
    command: buildAndPush
    Dockerfile: app/Dockerfile
    tags: latest